"""changed type of money amounts

Revision ID: e2c686a3654f
Revises: 0c148c8f3e45
Create Date: 2025-12-13 17:31:22.615020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2c686a3654f'
down_revision: Union[str, Sequence[str], None] = '0c148c8f3e45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('referral_rewards', 'amount',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=False)
    op.alter_column('users', 'ref_balance',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.drop_column('users', 'ref_total_earned')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ref_total_earned', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('users', 'ref_balance',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('referral_rewards', 'amount',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
